"""
Pydantic models for API data validation.
"""
from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field, field_validator
from app.core.validators import validate_query_text, validate_session_id


class DocumentUploadResponse(BaseModel):
    """Response when uploading a document."""
    status: str = Field(..., description="Operation status")
    document_id: str = Field(..., description="Unique document ID")
    filename: str = Field(..., description="File name")
    chunks_created: int = Field(..., description="Number of chunks created")
    message: Optional[str] = Field(None, description="Additional message")


class QueryRequest(BaseModel):
    """Chatbot query request."""
    query: str = Field(..., description="User question", min_length=1)
    
    @field_validator('query')
    @classmethod
    def validate_query(cls, v: str) -> str:
        """Validate and sanitize query."""
        return validate_query_text(v)


class ChunkInfo(BaseModel):
    """Information about a relevant chunk."""
    content: str = Field(..., description="Chunk content")
    score: float = Field(..., description="Relevance score")
    metadata: dict = Field(default_factory=dict, description="Chunk metadata")


class QueryResponse(BaseModel):
    """Chatbot response to a query (legacy)."""
    answer: str = Field(..., description="Response generated by the LLM")
    sources: List[str] = Field(default_factory=list, description="Source document IDs")
    relevant_chunks: List[ChunkInfo] = Field(default_factory=list, description="Retrieved relevant chunks")
    query: str = Field(..., description="Original question")


class WebResultInfo(BaseModel):
    """Information about a web search result."""
    title: str = Field(..., description="Result title")
    snippet: str = Field(..., description="Content description or snippet")
    url: str = Field(..., description="Result URL")


class QueryDocsResponse(BaseModel):
    """Chatbot response in documentation-only mode."""
    answer: str = Field(..., description="Response generated by the LLM (paraphrased)")
    sources: List[str] = Field(default_factory=list, description="Source document IDs")
    relevant_chunks: List[ChunkInfo] = Field(default_factory=list, description="Retrieved relevant chunks")
    query: str = Field(..., description="Original question")
    mode: str = Field(default="docs-only", description="Operation mode")


class QueryHybridResponse(BaseModel):
    """Chatbot response in hybrid mode (documentation + web)."""
    answer: str = Field(..., description="Response generated by the LLM (paraphrased)")
    sources_docs: List[str] = Field(default_factory=list, description="Source document IDs")
    sources_web: List[str] = Field(default_factory=list, description="Web source URLs")
    relevant_chunks: List[ChunkInfo] = Field(default_factory=list, description="Retrieved relevant chunks")
    web_results: List[WebResultInfo] = Field(default_factory=list, description="Web search results")
    query: str = Field(..., description="Original question")
    mode: str = Field(default="hybrid", description="Operation mode")


class DocumentInfo(BaseModel):
    """Information about a loaded document."""
    id: str = Field(..., description="Unique document ID")
    filename: str = Field(..., description="File name")
    uploaded_at: datetime = Field(..., description="Upload date")
    chunks_count: Optional[int] = Field(None, description="Number of chunks")
    file_size: Optional[int] = Field(None, description="File size in bytes")


class DocumentListResponse(BaseModel):
    """Response with document list."""
    documents: List[DocumentInfo] = Field(default_factory=list, description="List of documents")
    total: int = Field(..., description="Total number of documents")


class DeleteDocumentResponse(BaseModel):
    """Response when deleting a document."""
    status: str = Field(..., description="Operation status")
    document_id: str = Field(..., description="ID of deleted document")
    message: str = Field(..., description="Confirmation message")


class ErrorResponse(BaseModel):
    """Error response."""
    error: str = Field(..., description="Error message")
    detail: Optional[str] = Field(None, description="Additional error detail")


# Schemas for chat with memory
class ChatMessageRequest(BaseModel):
    """Chat message request with memory."""
    query: str = Field(..., description="User message", min_length=1)
    session_id: str = Field(..., description="Conversation session ID")
    mode: str = Field(default="docs", description="Search mode: 'docs' or 'hybrid'")
    
    @field_validator('query')
    @classmethod
    def validate_query(cls, v: str) -> str:
        """Validate and sanitize query."""
        return validate_query_text(v)
    
    @field_validator('session_id')
    @classmethod
    def validate_session_id(cls, v: str) -> str:
        """Validate session_id."""
        return validate_session_id(v)
    
    @field_validator('mode')
    @classmethod
    def validate_mode(cls, v: str) -> str:
        """Validate mode."""
        if v not in ['docs', 'hybrid']:
            return 'docs'  # Default to docs if invalid
        return v


class ChatMessageResponse(BaseModel):
    """Chat response with memory."""
    answer: str = Field(..., description="Response generated by the LLM")
    sources: List[str] = Field(default_factory=list, description="Source document IDs")
    relevant_chunks: List[ChunkInfo] = Field(default_factory=list, description="Retrieved relevant chunks")
    query: str = Field(..., description="Original message")
    session_id: str = Field(..., description="Session ID")
    mode: str = Field(default="docs", description="Mode used: 'docs' or 'hybrid'")
    sources_web: List[str] = Field(default_factory=list, description="Web source URLs (hybrid mode only)")
    web_results: List[WebResultInfo] = Field(default_factory=list, description="Web search results (hybrid mode only)")


class MessageHistory(BaseModel):
    """Message in conversation history."""
    role: str = Field(..., description="Message role (user/assistant)")
    content: str = Field(..., description="Message content")
    created_at: str = Field(..., description="Creation date")
    metadata: Optional[dict] = Field(None, description="Additional metadata")


class ConversationHistoryResponse(BaseModel):
    """Response with conversation history."""
    session_id: str = Field(..., description="Session ID")
    messages: List[MessageHistory] = Field(default_factory=list, description="List of messages")
    total: int = Field(..., description="Total number of messages")


class ClearConversationResponse(BaseModel):
    """Response when clearing conversation."""
    status: str = Field(..., description="Operation status")
    session_id: str = Field(..., description="Session ID")
    message: str = Field(..., description="Confirmation message")


class SessionInfo(BaseModel):
    """Information about a conversation session."""
    session_id: str = Field(..., description="Unique session ID")
    created_at: str = Field(..., description="Creation date")
    updated_at: str = Field(..., description="Last update date")
    message_count: int = Field(..., description="Number of messages in the session")


class SessionListResponse(BaseModel):
    """Response with session list."""
    sessions: List[SessionInfo] = Field(default_factory=list, description="List of sessions")
    total: int = Field(..., description="Total number of sessions")
